import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' show SemanticsAction;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:wisdom_app/models/favorite_item.dart';
import 'package:wisdom_app/screens/journal_screen.dart';
import 'package:wisdom_app/screens/keeper_screen.dart';
import 'package:wisdom_app/services/journal_owner_service.dart';
import 'package:wisdom_app/services/journal_pdf_builder.dart';

import 'journal_owner_test_helpers.dart';

/// Holds generation open until [release] is called -- used only to prove
/// the real-device transition/render repair: the preview surface must
/// stay stable and spinner-free for as long as generation is genuinely
/// still in flight. Delegates to a real [JournalPdfBuilder] once released,
/// so the actual generated bytes are never faked.
class _GatedPdfBuilder implements JournalPdfBuilder {
  _GatedPdfBuilder() : _delegate = JournalPdfBuilder();

  final JournalPdfBuilder _delegate;
  final Completer<void> _gate = Completer<void>();

  void release() {
    if (!_gate.isCompleted) _gate.complete();
  }

  @override
  Future<Uint8List> build({
    required List<FavoriteItem> items,
    String? ownerName,
    DateTime? now,
    bool compress = true,
  }) async {
    await _gate.future;
    return _delegate.build(
      items: items,
      ownerName: ownerName,
      now: now,
      compress: compress,
    );
  }
}

void main() {
  setUp(() {
    SharedPreferences.setMockInitialValues({});
  });

  FavoriteItem item({
    required String id,
    required String revealId,
    required String text,
    DateTime? keptAt,
  }) {
    return FavoriteItem(
      id: id,
      revealId: revealId,
      text: text,
      date: 'August 1, 2026',
      keptAt: (keptAt ?? DateTime.utc(2026, 7, 1)).toIso8601String(),
    );
  }

  testWidgets(
      'an empty Kept collection shows a quiet empty state -- no '
      'name prompt, no generation attempt, no PDF preview', (tester) async {
    await tester.pumpWidget(
      const MaterialApp(home: JournalScreen(items: [], isKeeper: true)),
    );
    await tester.pump();

    expect(find.text('Journal'), findsOneWidget);
    expect(
      find.byKey(const ValueKey('journal-empty-state')),
      findsOneWidget,
    );
    expect(find.byKey(const ValueKey('journal-name-field')), findsNothing);
    expect(find.byType(PdfPreview), findsNothing);
  });

  testWidgets(
      'the first-run name step offers optional name entry with Continue '
      'and Skip both present', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
        ),
      ),
    );
    await tester.pump();

    expect(
      find.byKey(const ValueKey('journal-name-field')),
      findsOneWidget,
    );
    expect(
      find.byKey(const ValueKey('journal-name-continue')),
      findsOneWidget,
    );
    expect(find.byKey(const ValueKey('journal-name-skip')), findsOneWidget);
  });

  testWidgets(
      'tapping Skip allows generation immediately with no name '
      'ever required, and reaches the PDF preview', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
        ),
      ),
    );
    await tester.pump();

    await tester.tap(find.byKey(const ValueKey('journal-name-skip')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    expect(find.byKey(const ValueKey('journal-name-field')), findsNothing);
    expect(find.byType(PdfPreview), findsOneWidget);

    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
    expect(await ownerService.loadName(), isNull);
    expect(await ownerService.hasHandledNamePrompt(), isTrue);
  });

  testWidgets('skipping once does not show the name step again on a later open',
      (tester) async {
    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
    await ownerService.skip();

    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
          journalOwnerService: ownerService,
        ),
      ),
    );
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    expect(find.byKey(const ValueKey('journal-name-field')), findsNothing);
    expect(find.byType(PdfPreview), findsOneWidget);
  });

  testWidgets(
      'entering a name and tapping Continue saves it (trimmed) and '
      'proceeds to generation', (tester) async {
    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());

    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
          journalOwnerService: ownerService,
        ),
      ),
    );
    await tester.pump();

    await tester.enterText(
      find.byKey(const ValueKey('journal-name-field')),
      '  Doğukan Işık  ',
    );
    await tester.tap(find.byKey(const ValueKey('journal-name-continue')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    expect(find.byType(PdfPreview), findsOneWidget);
    expect(await ownerService.loadName(), 'Doğukan Işık');
  });

  testWidgets(
      'leaving the name field empty and tapping Continue behaves '
      'like Skip -- generation is never blocked on an empty field',
      (tester) async {
    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());

    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
          journalOwnerService: ownerService,
        ),
      ),
    );
    await tester.pump();

    await tester.tap(find.byKey(const ValueKey('journal-name-continue')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    expect(find.byType(PdfPreview), findsOneWidget);
    expect(await ownerService.loadName(), isNull);
    expect(await ownerService.hasHandledNamePrompt(), isTrue);
  });

  testWidgets(
      'the name can be changed later from the preview stage without '
      'turning Journal into a settings screen', (tester) async {
    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
    await ownerService.saveName('Original Name');

    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
          journalOwnerService: ownerService,
        ),
      ),
    );
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));
    expect(find.byType(PdfPreview), findsOneWidget);

    await tester.tap(find.byKey(const ValueKey('journal-name-action')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 300));

    // Real-device repair: the approved full-field decision takeover
    // replaces the old rounded AlertDialog -- same Remove/Cancel/Save
    // meaning, now rendered as tracked text actions, and the redundant
    // "Journal name" heading is gone -- the name field itself is the
    // whole composition.
    expect(find.text('Journal name'), findsNothing);
    expect(
      find.byKey(const ValueKey('journal-name-decision')),
      findsOneWidget,
    );
    final nameField = tester.widget<TextField>(
      find.byKey(const ValueKey('journal-name-edit-field')),
    );
    expect(nameField.controller!.text, 'Original Name');
    expect(find.text('REMOVE'), findsOneWidget);

    await tester.tap(find.text('REMOVE'));
    await tester.pump();

    expect(await ownerService.loadName(), isNull);
  });

  testWidgets('CANCEL on the name edit leaves the existing name untouched',
      (tester) async {
    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
    await ownerService.saveName('Original Name');

    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
          journalOwnerService: ownerService,
        ),
      ),
    );
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    await tester.tap(find.byKey(const ValueKey('journal-name-action')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 300));

    await tester.enterText(
      find.byKey(const ValueKey('journal-name-edit-field')),
      'Never persisted',
    );
    await tester.tap(find.text('CANCEL'));
    await tester.pump();

    expect(
      find.byKey(const ValueKey('journal-name-decision')),
      findsNothing,
    );
    expect(await ownerService.loadName(), 'Original Name');
  });

  testWidgets('SAVE on the name edit persists the new name and regenerates',
      (tester) async {
    final ownerService =
        JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
    await ownerService.saveName('Original Name');

    await tester.pumpWidget(
      MaterialApp(
        home: JournalScreen(
          items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
          isKeeper: true,
          journalOwnerService: ownerService,
        ),
      ),
    );
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    await tester.tap(find.byKey(const ValueKey('journal-name-action')));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 300));

    await tester.enterText(
      find.byKey(const ValueKey('journal-name-edit-field')),
      'Renamed Owner',
    );
    await tester.tap(find.text('SAVE'));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 50));

    expect(
      find.byKey(const ValueKey('journal-name-decision')),
      findsNothing,
    );
    expect(await ownerService.loadName(), 'Renamed Owner');
    expect(find.byType(PdfPreview), findsOneWidget);
  });

  group('name edit keyboard stability', () {
    testWidgets(
        'the name edit overlay stays on the exact same visual axis while '
        'a keyboard inset appears and disappears -- no re-centering, and '
        'REMOVE/CANCEL/SAVE remain reachable throughout', (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.saveName('Original Name');

      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      await tester.tap(find.byKey(const ValueKey('journal-name-action')));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 300));

      final fieldFinder = find.byKey(const ValueKey('journal-name-edit-field'));
      final beforeKeyboard = tester.getTopLeft(fieldFinder);

      // Real-device repair: the Scaffold no longer auto-resizes for the
      // keyboard, so a simulated inset must not move the name field or
      // the action row at all.
      addTearDown(tester.view.resetViewInsets);
      tester.view.viewInsets = const FakeViewPadding(bottom: 300);
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(find.byType(AlertDialog), findsNothing);
      expect(tester.getTopLeft(fieldFinder), beforeKeyboard);
      expect(find.text('REMOVE'), findsOneWidget);
      expect(find.text('CANCEL'), findsOneWidget);
      expect(find.text('SAVE'), findsOneWidget);

      // Keyboard dismissing again must not move it back either -- there
      // was never anywhere else for it to be.
      tester.view.viewInsets = const FakeViewPadding();
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(tester.getTopLeft(fieldFinder), beforeKeyboard);
    });

    testWidgets(
        'SAVE still persists the new name while a keyboard inset is '
        'active', (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.saveName('Original Name');

      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      await tester.tap(find.byKey(const ValueKey('journal-name-action')));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 300));

      addTearDown(tester.view.resetViewInsets);
      tester.view.viewInsets = const FakeViewPadding(bottom: 300);
      await tester.pump();

      await tester.enterText(
        find.byKey(const ValueKey('journal-name-edit-field')),
        'Renamed With Keyboard Up',
      );
      await tester.tap(find.text('SAVE'));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(
        find.byKey(const ValueKey('journal-name-decision')),
        findsNothing,
      );
      expect(await ownerService.loadName(), 'Renamed With Keyboard Up');
    });

    testWidgets(
        'JournalScreen disables automatic keyboard-driven resize, so '
        'neither the overlay nor the content beneath it reflow',
        (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();

      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      final scaffold = tester.widget<Scaffold>(find.byType(Scaffold));
      expect(scaffold.resizeToAvoidBottomInset, isFalse);
    });
  });

  group('real-device transition/render repair', () {
    testWidgets(
        'no generic CircularProgressIndicator ever appears while Journal '
        'content is preparing, from first mount through a ready preview',
        (tester) async {
      final gatedBuilder = _GatedPdfBuilder();
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();

      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
            pdfBuilder: gatedBuilder,
          ),
        ),
      );

      // Still generating (the gate is held) -- no PdfPreview yet, and
      // critically, no generic loading indicator of any kind.
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));
      expect(find.byType(PdfPreview), findsNothing);
      expect(find.byType(CircularProgressIndicator), findsNothing);
      expect(find.byType(LinearProgressIndicator), findsNothing);

      gatedBuilder.release();
      await tester.pump();
      // The `printing` package rasterizes each page internally before the
      // preview is fully ready -- exactly the window its own default
      // `CircularProgressIndicator` would otherwise appear in.
      await tester.pump(const Duration(milliseconds: 20));
      expect(find.byType(CircularProgressIndicator), findsNothing);

      await tester.pump(const Duration(milliseconds: 200));
      expect(find.byType(PdfPreview), findsOneWidget);
      expect(find.byType(CircularProgressIndicator), findsNothing);
    });

    testWidgets(
        'the preview surface reserves stable top-level geometry (an '
        'AppBar and a Column with an Expanded reserved area) while '
        'generating, with no exception thrown across the reveal',
        (tester) async {
      final gatedBuilder = _GatedPdfBuilder();
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();

      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
            pdfBuilder: gatedBuilder,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(find.byType(AppBar), findsOneWidget);
      expect(find.text('Journal'), findsOneWidget);
      expect(find.byType(Expanded), findsWidgets);
      expect(tester.takeException(), isNull);

      gatedBuilder.release();
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 250));

      expect(find.byType(AppBar), findsOneWidget);
      expect(find.byType(PdfPreview), findsOneWidget);
      expect(tester.takeException(), isNull);
    });
  });

  // Visual-polish repair: Journal is openable by both Free and Keeper; only
  // the export action ("Take it with you") is entitlement-gated.
  group('Free vs Keeper gating', () {
    Future<void> reachPreview(
      WidgetTester tester, {
      required bool isKeeper,
      JournalShareHandler? shareHandler,
    }) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();
      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: isKeeper,
            journalOwnerService: ownerService,
            shareHandler: shareHandler,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));
    }

    testWidgets(
        'a Free user reaches the real preview and can read/navigate it -- '
        'no entry paywall', (tester) async {
      await reachPreview(tester, isKeeper: false);

      expect(find.byType(KeeperScreen), findsNothing);
      expect(find.byType(PdfPreview), findsOneWidget);
      // Real-device repair: "Gather what you kept." was removed entirely
      // -- nothing outranks the publication itself.
      expect(find.text('Gather what you kept.'), findsNothing);
    });

    testWidgets(
        'a Free user cannot trigger native sharing through PdfPreview\'s '
        'own built-in controls', (tester) async {
      await reachPreview(tester, isKeeper: false);

      final preview = tester.widget<PdfPreview>(find.byType(PdfPreview));
      expect(preview.allowSharing, isFalse);
      expect(preview.allowPrinting, isFalse);
      expect(preview.useActions, isFalse);
    });

    testWidgets(
        'a Keeper also cannot bypass the single export entry via '
        'PdfPreview\'s own built-in controls', (tester) async {
      await reachPreview(tester, isKeeper: true);

      final preview = tester.widget<PdfPreview>(find.byType(PdfPreview));
      expect(preview.allowSharing, isFalse);
      expect(preview.allowPrinting, isFalse);
      expect(preview.useActions, isFalse);
    });

    testWidgets(
        'a Free user sees "Take it with you." with a muted "Available '
        'with Keeper." note beneath it', (tester) async {
      await reachPreview(tester, isKeeper: false);

      expect(find.text('Take it with you.'), findsOneWidget);
      expect(
        find.byKey(const ValueKey('journal-keeper-note')),
        findsOneWidget,
      );
      expect(find.text('Available with Keeper.'), findsOneWidget);
    });

    testWidgets(
        'a Free user tapping "Take it with you." opens the existing '
        'Keeper screen -- no custom/second paywall', (tester) async {
      var shareCalled = false;
      await reachPreview(
        tester,
        isKeeper: false,
        shareHandler: (bytes, filename) async {
          shareCalled = true;
          return true;
        },
      );

      // `pumpAndSettle` is avoided here (as in every other test in this
      // file that reaches the PdfPreview stage): the real `printing`-
      // package preview widget never fully quiesces, so bounded pumps are
      // used instead.
      await tester.tap(find.byKey(const ValueKey('journal-take-action')));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 300));

      expect(find.byType(KeeperScreen), findsOneWidget);
      expect(shareCalled, isFalse);
    });

    testWidgets(
        'a Keeper reaches the exact same Journal screen and real '
        'preview -- no separate premium Journal UI', (tester) async {
      await reachPreview(tester, isKeeper: true);

      expect(find.byType(PdfPreview), findsOneWidget);
      // Real-device repair: "Gather what you kept." was removed entirely
      // -- nothing outranks the publication itself.
      expect(find.text('Gather what you kept.'), findsNothing);
      expect(find.text('Take it with you.'), findsOneWidget);
    });

    testWidgets('a Keeper never sees "Available with Keeper."', (tester) async {
      await reachPreview(tester, isKeeper: true);

      expect(
        find.byKey(const ValueKey('journal-keeper-note')),
        findsNothing,
      );
      expect(find.text('Available with Keeper.'), findsNothing);
    });

    testWidgets(
        'a Keeper tapping "Take it with you." invokes native share '
        'behavior with the actual generated PDF bytes -- never opening '
        'Keeper', (tester) async {
      Uint8List? sharedBytes;
      String? sharedFilename;
      await reachPreview(
        tester,
        isKeeper: true,
        shareHandler: (bytes, filename) async {
          sharedBytes = bytes;
          sharedFilename = filename;
          return true;
        },
      );

      await tester.tap(find.byKey(const ValueKey('journal-take-action')));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(find.byType(KeeperScreen), findsNothing);
      expect(sharedBytes, isNotNull);
      expect(sharedBytes, isNotEmpty);
      expect(sharedFilename, 'Journal.pdf');
    });
  });

  group('Voice Control actionability (Build 33 real-device repair)', () {
    testWidgets('Back has SemanticsAction.tap', (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();
      await tester.pumpWidget(
        MaterialApp(
          home: Builder(
            builder: (context) => TextButton(
              onPressed: () {
                Navigator.of(context).push<void>(
                  MaterialPageRoute<void>(
                    builder: (context) => JournalScreen(
                      items: [
                        item(id: '1', revealId: 'r-1', text: 'A wisdom.')
                      ],
                      isKeeper: true,
                      journalOwnerService: ownerService,
                    ),
                  ),
                );
              },
              child: const Text('Open Journal'),
            ),
          ),
        ),
      );
      await tester.tap(find.text('Open Journal'));
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      final semantics = tester.ensureSemantics();
      final node = tester.getSemantics(
        find.byKey(const ValueKey('east-back-button')),
      );
      expect(node.getSemanticsData().hasAction(SemanticsAction.tap), isTrue);
      semantics.dispose();
    });

    // ROOT CAUSE: the outer `Semantics` for the Add/Change-name AppBar
    // action carried a `label` and `button: true` but no `onTap` --
    // `ExcludeSemantics` below discarded the inner `TextButton`'s own
    // handler, so no real `SemanticsAction.tap` reached the platform.
    // Fixed with the same `onTap`-mirroring pattern used everywhere else
    // this session.
    testWidgets('Add/Edit Name has a label and SemanticsAction.tap',
        (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();
      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      final semantics = tester.ensureSemantics();
      final node = tester.getSemantics(
        find.byKey(const ValueKey('journal-name-action')),
      );
      expect(node.label, 'Add name');
      expect(node.getSemanticsData().hasAction(SemanticsAction.tap), isTrue);
      semantics.dispose();
    });

    // ROOT CAUSE: same missing-`onTap` defect on `_takeItWithYouAction`'s
    // outer `Semantics`. Also verifies the export action's semantic
    // truthfulness in the gated (non-Keeper) state: tapping it genuinely
    // opens Keeper (see `_handleTakeItWithYou`), so it must remain a real
    // actionable control with a hint describing that outcome, not a
    // silent no-op dressed up as a button.
    testWidgets('Export/Take it with you has SemanticsAction.tap for a Keeper',
        (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();
      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A wisdom.')],
            isKeeper: true,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      final semantics = tester.ensureSemantics();
      final node = tester.getSemantics(
        find.byKey(const ValueKey('journal-take-action')),
      );
      expect(node.label, 'Take it with you.');
      expect(node.hint, isEmpty);
      expect(node.getSemanticsData().hasAction(SemanticsAction.tap), isTrue);
      semantics.dispose();
    });

    testWidgets(
        'Export/Take it with you has SemanticsAction.tap and a truthful '
        'hint when Keeper-gated (tapping genuinely opens Keeper)',
        (tester) async {
      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();
      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A wisdom.')],
            isKeeper: false,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      final semantics = tester.ensureSemantics();
      final node = tester.getSemantics(
        find.byKey(const ValueKey('journal-take-action')),
      );
      expect(node.label, 'Take it with you. Available with Keeper.');
      expect(node.hint, 'Opens Keeper.');
      expect(node.getSemanticsData().hasAction(SemanticsAction.tap), isTrue,
          reason: 'tapping this genuinely opens Keeper -- it must never be '
              'presented as non-actionable.');
      semantics.dispose();
    });
  });

  group('Dynamic Type (Build 33 accessibility repair)', () {
    testWidgets(
        'the first-time name prompt stays usable at 100/135/160/200% '
        'text scale', (tester) async {
      for (final scale in [1.0, 1.35, 1.6, 2.0]) {
        tester.platformDispatcher.textScaleFactorTestValue = scale;
        addTearDown(
          tester.platformDispatcher.clearTextScaleFactorTestValue,
        );

        await tester.pumpWidget(
          MaterialApp(
            home: JournalScreen(
              items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
              isKeeper: true,
            ),
          ),
        );
        await tester.pump();

        expect(
          find.byKey(const ValueKey('journal-name-field')),
          findsOneWidget,
          reason: 'the name field must remain reachable at ${scale}x.',
        );
        expect(
          find.byKey(const ValueKey('journal-name-skip')),
          findsOneWidget,
          reason: 'Skip must remain reachable at ${scale}x.',
        );
        expect(tester.takeException(), isNull);
      }
    });

    testWidgets('the PDF preview stays usable at 200% text scale',
        (tester) async {
      tester.platformDispatcher.textScaleFactorTestValue = 2.0;
      addTearDown(
        tester.platformDispatcher.clearTextScaleFactorTestValue,
      );

      final ownerService =
          JournalOwnerService(ownerStore: InMemoryJournalOwnerStore());
      await ownerService.skip();
      await tester.pumpWidget(
        MaterialApp(
          home: JournalScreen(
            items: [item(id: '1', revealId: 'r-1', text: 'A kept wisdom.')],
            isKeeper: false,
            journalOwnerService: ownerService,
          ),
        ),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 50));

      expect(find.byType(PdfPreview), findsOneWidget);
      expect(tester.takeException(), isNull);
    });
  });
}
