name: wisdom_app
description: A minimal wisdom app
publish_to: "none"

version: 1.0.0+25
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.2.0
  url_launcher: ^6.3.1
  share_plus: ^13.2.1
  flutter_local_notifications: ^22.1.0
  flutter_timezone: ^5.1.0
  timezone: ^0.11.1

  shared_preferences: ^2.2.2
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  in_app_purchase_platform_interface: ^1.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/objects/

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Light.ttf
          weight: 300

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
